services:
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend
    command: yarn run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build: ./backend
    container_name: backend
    command: pipenv run dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/src
