services:
  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend
    command: pipenv run dev
    ports:
      - "8000:8000"
